version: '1.0'
stages:
- clone
- buildAndTest
steps:
  main_clone:
    stage: clone
    title: Cloning main repository...
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: github-guy
  MyAppDockerImage:
    stage: buildAndTest
    title: Building Docker Multi-stage Image
    type: build
    image_name: my-golang-image
    working_directory: ./
    tag: '${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile.multistage
